/**
 * Preview API Route
 * Handles enabling/disabling Next.js draft mode for Strapi content preview
 *
 * This route is called by Strapi's Preview feature to enable draft mode
 * before redirecting to the preview page.
 */

import { draftMode } from 'next/headers';
import { redirect } from 'next/navigation';

export async function GET(request: Request) {
  // Parse query string parameters
  const { searchParams } = new URL(request.url);
  const secret = searchParams.get('secret');
  const url = searchParams.get('url');
  const status = searchParams.get('status');

  // Check the secret parameter
  // This secret should only be known to this route handler and Strapi
  if (secret !== process.env.PREVIEW_SECRET) {
    return new Response('Invalid token', { status: 401 });
  }

  // Validate that URL is provided
  if (!url) {
    return new Response('Missing url parameter', { status: 400 });
  }

  // Enable or disable Draft Mode based on the content status
  if (status === 'published') {
    // Disable draft mode for published content
    (await draftMode()).disable();
  } else {
    // Enable draft mode for draft content
    (await draftMode()).enable();
  }

  // Redirect to the path from Strapi
  // We don't redirect to arbitrary URLs to prevent open redirect vulnerabilities
  // The URL is generated by Strapi's preview handler which we control
  redirect(url);
}
